// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ticket_system_web_app.Data;

#nullable disable

namespace ticket_system_web_app.Migrations
{
    [DbContext(typeof(TicketSystemDbContext))]
    [Migration("20250408012747_InitCreation")]
    partial class InitCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeGroup", b =>
                {
                    b.Property<int>("EmployeesEId")
                        .HasColumnType("int");

                    b.Property<int>("GroupsExistingInGId")
                        .HasColumnType("int");

                    b.HasKey("EmployeesEId", "GroupsExistingInGId");

                    b.HasIndex("GroupsExistingInGId");

                    b.ToTable("group_member", (string)null);
                });

            modelBuilder.Entity("ticket_system_web_app.Models.BoardState", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("state_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int")
                        .HasColumnName("board_id");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state_name");

                    b.HasKey("StateId");

                    b.HasIndex("BoardId");

                    b.ToTable("BoardStates");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.Employee", b =>
                {
                    b.Property<int>("EId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("e_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("f_name");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hashed_password");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_admin");

                    b.Property<bool?>("IsManager")
                        .HasColumnType("bit")
                        .HasColumnName("is_manager");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("l_name");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("EId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EId = 1,
                            Email = "admin@temp.com",
                            FName = "admin",
                            HashedPassword = "$2a$11$tqFhRcVPxPe/F7g4i2.9c.tms9AlneY5RDZb1SipsY1FQtMcaaecu",
                            IsActive = true,
                            IsAdmin = true,
                            IsManager = true,
                            LName = "admin",
                            Username = "tempAdmin"
                        });
                });

            modelBuilder.Entity("ticket_system_web_app.Models.Group", b =>
                {
                    b.Property<int>("GId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("g_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GId"));

                    b.Property<string>("GDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("g_description");

                    b.Property<string>("GName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("g_name");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.HasKey("GId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.Project", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("p_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PId"));

                    b.Property<int?>("EmployeeEId")
                        .HasColumnType("int");

                    b.Property<string>("PDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("p_description");

                    b.Property<string>("PTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("p_title");

                    b.Property<int>("ProjectLeadId")
                        .HasColumnType("int")
                        .HasColumnName("project_lead_id");

                    b.HasKey("PId");

                    b.HasIndex("EmployeeEId");

                    b.HasIndex("ProjectLeadId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.ProjectBoard", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("board_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoardId"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("p_id");

                    b.HasKey("BoardId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ProjectBoards");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.ProjectGroup", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<int?>("GroupGId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectPId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "GroupId");

                    b.HasIndex("GroupGId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ProjectPId");

                    b.ToTable("ProjectGroups");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.ProjectTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("int")
                        .HasColumnName("assignee_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("state_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.HasKey("TaskId");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("StateId");

                    b.ToTable("task");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.StateAssignedGroup", b =>
                {
                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("StateId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("StateAssignedGroups");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.TaskChange", b =>
                {
                    b.Property<int>("ChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("change_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChangeId"));

                    b.Property<int>("AssigneeId")
                        .HasColumnType("int")
                        .HasColumnName("assignee_id");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("changed_date");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("previous_value");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("ChangeId");

                    b.HasIndex("AssigneeId");

                    b.ToTable("TaskChanges");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.TaskChangeLog", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.Property<int>("ChangeId")
                        .HasColumnType("int")
                        .HasColumnName("change_id");

                    b.HasKey("TaskId", "ChangeId");

                    b.HasIndex("ChangeId");

                    b.ToTable("TaskChangeLogs");
                });

            modelBuilder.Entity("EmployeeGroup", b =>
                {
                    b.HasOne("ticket_system_web_app.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesEId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ticket_system_web_app.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsExistingInGId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ticket_system_web_app.Models.BoardState", b =>
                {
                    b.HasOne("ticket_system_web_app.Models.ProjectBoard", "ProjectBoard")
                        .WithMany("States")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectBoard");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.Project", b =>
                {
                    b.HasOne("ticket_system_web_app.Models.Employee", null)
                        .WithMany("ProjectsLeading")
                        .HasForeignKey("EmployeeEId");

                    b.HasOne("ticket_system_web_app.Models.Employee", "ProjectLead")
                        .WithMany()
                        .HasForeignKey("ProjectLeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectLead");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.ProjectBoard", b =>
                {
                    b.HasOne("ticket_system_web_app.Models.Project", "Project")
                        .WithOne("ProjectBoard")
                        .HasForeignKey("ticket_system_web_app.Models.ProjectBoard", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.ProjectGroup", b =>
                {
                    b.HasOne("ticket_system_web_app.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupGId");

                    b.HasOne("ticket_system_web_app.Models.Group", null)
                        .WithMany("Collaborations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ticket_system_web_app.Models.Project", null)
                        .WithMany("Collaborators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ticket_system_web_app.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectPId");

                    b.Navigation("Group");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.ProjectTask", b =>
                {
                    b.HasOne("ticket_system_web_app.Models.Employee", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ticket_system_web_app.Models.BoardState", "BoardState")
                        .WithMany("Tasks")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("BoardState");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.StateAssignedGroup", b =>
                {
                    b.HasOne("ticket_system_web_app.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ticket_system_web_app.Models.BoardState", "BoardState")
                        .WithMany("AssignedGroups")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardState");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.TaskChange", b =>
                {
                    b.HasOne("ticket_system_web_app.Models.Employee", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.TaskChangeLog", b =>
                {
                    b.HasOne("ticket_system_web_app.Models.TaskChange", "TaskChange")
                        .WithMany()
                        .HasForeignKey("ChangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ticket_system_web_app.Models.ProjectTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("TaskChange");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.BoardState", b =>
                {
                    b.Navigation("AssignedGroups");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.Employee", b =>
                {
                    b.Navigation("ProjectsLeading");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.Group", b =>
                {
                    b.Navigation("Collaborations");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.Project", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("ProjectBoard");
                });

            modelBuilder.Entity("ticket_system_web_app.Models.ProjectBoard", b =>
                {
                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
